[package]
name = "length-prefixed-stream"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.9.0"
desert = "2.0.0"
futures = "0.3.12"
futures-core = "0.3.12"
pin-project-lite = "0.2.4"
